# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proizvod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('naziv', models.CharField(default='', max_length=30)),
                ('napomena', models.CharField(default='', max_length=500)),
                ('cena', models.FloatField()),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Klijent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='', max_length=30)),
                ('prezime', models.CharField(default='', max_length=30)),
                ('napomena', models.CharField(default='', max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Radnik',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ime', models.CharField(default='', max_length=30)),
                ('prezime', models.CharField(default='', max_length=30)),
                ('plata', models.FloatField()),
                ('jmbg', models.CharField(max_length=12)),
                ('napomena', models.CharField(default='', max_length=500)),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Usluga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cena', models.FloatField()),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('napomena', models.CharField(default='', max_length=500)),
                ('status', models.IntegerField(choices=[(1, 'PLACENO'), (2, 'NEPLACENO'), (3, 'VRACENO')])),
                ('proizvod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Proizvod')),
                ('klijent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Klijent')),
                ('radnik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='v1.Radnik')),
            ],
        ),
    ]
