# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-02 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='radnik',
            old_name='date',
            new_name='created',
        ),
        migrations.RenameField(
            model_name='usluga',
            old_name='date',
            new_name='created',
        ),
    ]
