# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-15 15:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1', '0002_auto_20190902_1129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proizvod',
            name='naziv',
            field=models.CharField(default='', max_length=200),
        ),
    ]
